// The MongoDB v1 Source Profile — the single source of truth for "what the sizing needs"
// (spec §9), behind the D4/§17 profile seam. Pure data, zero logic. The 6 required signals
// map 1:1 to SizingInputs (src/engine/types.ts); recommended/optional populate the coverage
// matrix and (for tcoCritical ones) the "what to collect" asks.

import type { SourceProfile, SignalSpec } from './types';

const required: SignalSpec[] = [
  {
    id: 'cluster.shardCount',
    label: 'Shard count (data-bearing replica-set count)',
    unit: 'count',
    valueKind: 'scalar',
    criticality: 'required',
    defaultable: false,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text', 'vision'],
    aliases: ['shards', 'shard count', 'number of shards', 'sh.status'],
    engineSlot: 'shards',
    collectRequest: 'Number of shards (data-bearing replica sets) in the cluster — from `sh.status()` or the Ops Manager/Atlas deployment view.',
    collectWhy: 'Linear multiplier on every consumed-ECPU figure; no sizing number can be produced without it.',
  },
  {
    id: 'node.hoVcpu',
    label: 'vCPU per data-bearing node — home/primary region',
    unit: 'vCPU',
    valueKind: 'scalar',
    criticality: 'required',
    defaultable: false,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text', 'vision'],
    aliases: ['hovcpu', 'cores per node', 'vcpu per node', 'primary cores', 'node cores'],
    engineSlot: 'hoVcpu',
    collectRequest: 'vCPU/cores per data-bearing node in the primary region (instance type, `nproc`/`lscpu`, or hardware spec).',
    collectWhy: 'Converts CPU-utilization % into absolute ECPU for both the primary and HA-secondary roles. NOTE: v1 assumes home-region members are homogeneous (same instance size); a heterogeneous HA-secondary tier is a known limitation flagged at triage.',
  },
  {
    id: 'node.drVcpu',
    label: 'vCPU per data-bearing node — DR region',
    unit: 'vCPU',
    valueKind: 'scalar',
    criticality: 'required',
    defaultable: true,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text', 'vision'],
    aliases: ['drvcpu', 'dr cores', 'dr vcpu', 'dr region cores'],
    engineSlot: 'drVcpu',
    collectRequest: 'vCPU/cores per data-bearing node in the DR region (if it differs from the primary region).',
    collectWhy: 'Sizes the DR-region ECPU in the full-cluster scope. Defaultable to the home-region vCPU if DR mirrors home — but that is a flagged assumption, not a measurement.',
  },
  {
    id: 'util.primary',
    label: 'System-CPU utilization — primary role (avg & peak)',
    unit: 'fraction 0-1',
    valueKind: 'avgPeak',
    criticality: 'required',
    defaultable: false,
    derivableBy: ['numeric-series', 'vision', 'manual'],
    aliases: ['system cpu', 'cpu utilization', 'process cpu', 'primary cpu', 'cpu percent'],
    engineSlot: 'util.primary',
    collectRequest: 'Average AND peak System-CPU % on the primaries over a representative window — a metrics CSV/export is strongly preferred over a screenshot.',
    collectWhy: 'The core ECPU driver. Read natively from a series when possible (exact); a chart screenshot can only be read approximately by vision.',
  },
  {
    id: 'util.hoSec',
    label: 'System-CPU utilization — home-region HA secondary (avg & peak)',
    unit: 'fraction 0-1',
    valueKind: 'avgPeak',
    criticality: 'required',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision', 'manual'],
    aliases: ['secondary cpu', 'ha secondary cpu', 'electable secondary cpu', 'secondary system cpu'],
    engineSlot: 'util.hoSec',
    collectRequest: 'Average AND peak System-CPU % on the home-region secondaries (electable/analytics members).',
    collectWhy: 'Summed into the full-cluster ECPU. Defaultable as a fraction of the primary — a flagged assumption.',
  },
  {
    id: 'util.dr',
    label: 'System-CPU utilization — DR region (avg & peak)',
    unit: 'fraction 0-1',
    valueKind: 'avgPeak',
    criticality: 'required',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision', 'manual'],
    aliases: ['dr cpu', 'dr region cpu', 'disaster recovery cpu', 'dr system cpu'],
    engineSlot: 'util.dr',
    collectRequest: 'Average AND peak System-CPU % on the DR-region nodes.',
    collectWhy: 'Summed into the full-cluster ECPU. Defaultable to a replication-only level — a flagged assumption.',
  },
  {
    id: 'data.storageSizeGb',
    label: 'On-disk / logical storage size estimate',
    unit: 'GB',
    valueKind: 'scalar',
    criticality: 'required',
    defaultable: true,
    tcoCritical: true,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text', 'numeric-series', 'vision'],
    aliases: ['storage size', 'storagesize', 'disk usage', 'compressed data size'],
    // No engineSlot: it doesn't feed the ECPU compute — it feeds the ADB storage cost line, the cold-DR
    // RTO, and the cost-research prompt. It is required because it drives the dominant TCO figure; a
    // missing value must block (or be a flagged rep assumption), never a silent default.
    collectRequest: 'On-disk storage size after WiredTiger compression (`db.stats().storageSize`, or disk-usage metric).',
    collectWhy: 'The ADB storage line + migration volume — the dominant cost driver. Mark it compressed (on-disk) or uncompressed (logical) via the compression-state companion; an uncompressed figure is divided by the Oracle compression factor.',
  },
];

const recommended: SignalSpec[] = [
  {
    id: 'topology.nodesPerShard',
    label: 'Data-bearing nodes per shard (replica-set members)',
    unit: 'count',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text'],
    aliases: ['nodes per shard', 'replica set members', 'rs members', 'members per shard'],
    collectRequest: 'Replica-set members per shard (primary + electable + hidden/analytics + DR).',
    collectWhy: 'Defines which roles exist and suggests the Peak÷N divisor default; not read directly by the engine.',
  },
  {
    id: 'data.logicalSizeGb',
    label: 'Logical data size',
    unit: 'GB',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    tcoCritical: true,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text', 'numeric-series'],
    aliases: ['logical data size', 'data size', 'datasize', 'db.stats datasize'],
    collectRequest: 'Total logical data size (`db.stats().dataSize` summed, or the Ops Manager/Atlas "Logical Data Size").',
    collectWhy: 'Storage is ~79% of the Northwind bill — the dominant TCO line. The ECPU number survives without it, but the cost case does not.',
  },
  {
    id: 'data.storageCompressionState',
    label: 'Storage figure: compressed (on-disk) or uncompressed (logical)',
    valueKind: 'enum',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['llm-text', 'keyvalue', 'vision'],
    aliases: ['compressed', 'uncompressed', 'on-disk', 'on disk', 'logical data', 'before compression', 'after compression'],
    collectRequest: 'Is the storage figure on-disk (compressed) or logical (uncompressed)? Default: uncompressed.',
    collectWhy: 'Determines whether the Oracle compression factor is applied to the storage estimate (uncompressed -> divided by the factor).',
  },
  {
    id: 'data.indexSizeGb',
    label: 'Total index size',
    unit: 'GB',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['keyvalue', 'table-lookup', 'numeric-series'],
    aliases: ['index size', 'indexsize', 'total index size'],
    collectRequest: 'Total index size (`db.stats().indexSize` or `collStats` totalIndexSize).',
    collectWhy: 'Adds to billed storage and hot-RAM pressure.',
  },
  {
    id: 'workingSetGb',
    label: 'Working-set size',
    unit: 'GB',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision', 'llm-text'],
    aliases: ['working set', 'working set size', 'hot data size', 'cache working set'],
    collectRequest: 'Approximate working-set size (WiredTiger cache pressure / bytes-into-cache, or a stated estimate).',
    collectWhy: 'With node RAM gives the RAM:data ratio that validates trust in the CPU-utilization model.',
  },
  {
    id: 'node.ramGb',
    label: 'RAM per data-bearing node',
    unit: 'GB',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text'],
    aliases: ['node ram', 'ram per node', 'memory per node', 'wiredtiger cache size'],
    collectRequest: 'RAM per data-bearing node (instance type, `free`, or WiredTiger cacheSizeGB).',
    collectWhy: 'Validates the CPU-util model is not masking a RAM-bound workload.',
  },
  {
    id: 'node.atlasTier',
    label: 'Atlas cluster tier (M10–M300)',
    valueKind: 'enum',
    criticality: 'recommended',
    defaultable: true,
    // No engineSlot: triage resolves the tier -> vCPU via ENGINE_CONFIG.atlasTierVcpu (table-lookup),
    // synthesizing node.hoVcpu/node.drVcpu. Aliases deliberately exclude tier codes (M80, …) — those are
    // too short and would substring-match noisily; the tier string is read by vision/llm-text instead.
    derivableBy: ['vision', 'llm-text', 'keyvalue'],
    aliases: ['instance size', 'cluster tier', 'atlas tier', 'instancesize', 'tier'],
    collectRequest: 'Atlas cluster tier from the Atlas console or cluster-describe JSON (e.g. M80).',
    collectWhy: 'Enables a deterministic vCPU lookup from the tier table without a manual vCPU entry.',
  },
  {
    id: 'disk.iops',
    label: 'Disk IOPS (avg & peak)',
    unit: 'IOPS',
    valueKind: 'avgPeak',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision'],
    aliases: ['disk iops', 'iops', 'disk io', 'io operations'],
    collectRequest: 'Average and peak disk IOPS over a representative window.',
    collectWhy: 'Confirms the workload is not I/O-bound and feeds the storage-class cost.',
  },
  {
    id: 'workload.opsPerSec',
    label: 'Operations per second (avg & peak)',
    unit: 'ops/sec',
    valueKind: 'avgPeak',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision', 'llm-text'],
    aliases: ['ops per sec', 'opcounters', 'operations per second', 'ops/sec'],
    collectRequest: 'Average and peak ops/sec (opcounters: read/write/command).',
    collectWhy: 'Corroborates the CPU-utilization model and the read-offload story.',
  },
  {
    id: 'workload.concurrency',
    label: 'Concurrency (avg & peak)',
    unit: 'count',
    valueKind: 'avgPeak',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision'],
    aliases: ['concurrency', 'active connections', 'connections', 'active tickets'],
    collectRequest: 'Average and peak concurrency (active connections or WiredTiger tickets).',
    collectWhy: 'Informs the 2x/3x autoscale ceiling choice.',
  },
  {
    id: 'workload.oplogGbPerHour',
    label: 'Oplog churn',
    unit: 'GB/hour',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['numeric-series', 'keyvalue', 'llm-text'],
    aliases: ['oplog gb/hour', 'oplog churn', 'oplog throughput', 'oplog gb per hour'],
    collectRequest: 'Oplog GB/hour (or oplog window + oplog size).',
    collectWhy: 'Sizes write-heavy load and the DR replication cost.',
  },
  {
    id: 'mongo.edition',
    label: 'MongoDB edition',
    valueKind: 'enum',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['llm-text', 'keyvalue', 'vision'],
    aliases: ['mongodb edition', 'edition', 'enterprise advanced', 'community edition'],
    collectRequest: 'MongoDB edition (Community, Enterprise Advanced, Atlas tier).',
    collectWhy: 'Selects the on-prem Enterprise license line in the TCO.',
  },
  {
    id: 'workload.readPreference',
    label: 'Read preference',
    valueKind: 'enum',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['llm-text', 'keyvalue'],
    aliases: ['read preference', 'readpreference', 'reads to secondaries', 'secondary reads'],
    collectRequest: 'Application read preference (primary, secondaryPreferred, etc.).',
    collectWhy: 'Explains secondary CPU and the read-offload narrative.',
  },
  {
    id: 'growth.annualPct',
    label: 'Annual growth rate',
    unit: '%/year',
    valueKind: 'scalar',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['llm-text'],
    aliases: ['growth rate', 'annual growth', 'yearly growth', 'data growth'],
    collectRequest: 'Expected annual data/workload growth rate (a stated figure from the customer).',
    collectWhy: 'Drives the 5-year projection streams. v1 takes this as a stated assumption only — never a fitted trend.',
  },
  {
    id: 'dr.posture',
    label: 'DR posture',
    valueKind: 'enum',
    criticality: 'recommended',
    defaultable: true,
    derivableBy: ['llm-text', 'keyvalue'],
    aliases: ['dr posture', 'disaster recovery', 'dr strategy', 'bcp'],
    collectRequest: 'Required DR posture (none / cold pilot-light / warm standby) and RTO/RPO.',
    collectWhy: 'Selects the cold vs warm DR cost add (>$100K/yr swing for Northwind).',
  },
];

const optional: SignalSpec[] = [
  {
    id: 'data.collectionProfile',
    label: 'Per-collection profile',
    unit: 'mixed',
    valueKind: 'scalar',
    criticality: 'optional',
    defaultable: true,
    derivableBy: ['keyvalue', 'table-lookup', 'llm-text'],
    aliases: ['collection profile', 'collstats', 'per-collection breakdown', 'collection stats'],
    collectRequest: 'Per-collection size/op breakdown, if available.',
    collectWhy: 'Refines hot-collection identification and migration sequencing.',
  },
  {
    id: 'network.egressGbMonth',
    label: 'Network egress',
    unit: 'GB/month',
    valueKind: 'scalar',
    criticality: 'optional',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision'],
    aliases: ['network egress', 'egress', 'network throughput', 'egress gb/month'],
    collectRequest: 'Cross-region network egress GB/month, if available.',
    collectWhy: 'Refines the warm-DR egress cost.',
  },
  {
    id: 'workload.peakWindow',
    label: 'Peak window',
    valueKind: 'enum',
    criticality: 'optional',
    defaultable: true,
    derivableBy: ['numeric-series', 'vision', 'llm-text'],
    aliases: ['peak window', 'peak hours', 'batch window', 'peak period'],
    collectRequest: 'When peaks occur and how long they last (e.g. end-of-month batch).',
    collectWhy: 'Refines the Peak÷N divisor and the autoscale band.',
  },
];

export const MONGODB_PROFILE: SourceProfile = {
  id: 'mongodb',
  signalSchema: { signals: [...required, ...recommended, ...optional] },
  thresholds: {
    methodCap: {
      'numeric-series': 1,
      keyvalue: 1,
      'table-lookup': 1,
      manual: 1,
      'llm-text': 0.75,
      vision: 0.7,
      heuristic: 0.6,
      'assumption-default': 0.5,
    },
    missingFloor: 0.2,
    // A vision read is capped at 0.70 (that is as good as reading a value off an image gets), so the
    // engineering-grade floor is 0.70 — a confident vision-sourced signal IS engineering-grade, not a
    // perpetual "directional". engMean sits a hair under 0.70 so an all-vision sizing still qualifies
    // (the mean of six 0.70s drifts to 0.6999… in float). Heuristic (0.60) / assumption-default (0.50)
    // stay below the floor, so a fuzzy or defaulted signal still reads as needs-confirmation.
    engFloor: 0.7,
    engMean: 0.69,
  },
};
